import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Fotos de producto ────────────────────────────────────────────────────────
// Packshots descargados de las casas (Dom Pérignon, GH Mumm, Terrazas de los
// Andes) y de distribuidores premium, recortados sobre el fondo oscuro de la
// marca. Archivos en public/productos/.
// Los vintages de una misma etiqueta comparten botella.
const IMG_BY_SKU: Record<string, string> = {
  // ── piezas incorporadas en agosto de 2026
  "90001": "am-brut-nature-blanco",
  "90002": "am-brut-nature-rosado",
  "90003": "am-cab-franc-cab-sauv",
  "90004": "am-chardonnay",
  "90005": "am-gsm",
  "90006": "am-malbec",
  "90007": "am-pinot-noir",
  "90008": "am-semillon",
  "90009": "an-bdb-magnum",
  "90010": "an-blanc-de-blancs",
  "90011": "an-blanco",
  "90012": "an-brut-nature-rose",
  "90013": "an-gran-magnum",
  "90014": "an-gran-magnum-esp",
  "90015": "an-orange",
  "90016": "an-tinto",
  "90017": "barsol-acholado",
  "90018": "barsol-italia",
  "90019": "barsol-moscatel",
  "90020": "barsol-quebranta",
  "90021": "barsol-torontel",
  "90022": "bruich-18",
  "90023": "bruich-30",
  "90024": "caro-aruma",
  "90025": "caro-caro",
  "90026": "caro-petit",
  "90027": "caro-petit-5l",
  "90028": "cdh-cabernet-franc",
  "90029": "cdh-corte-blancas",
  "90030": "cdh-malbec",
  "90031": "cdh-pinot-noir",
  "90032": "cdh-rose",
  "90033": "cdp-cabernet-franc",
  "90034": "cdp-corte-blancas",
  "90035": "cdp-extra-brut",
  "90036": "cdp-extra-brut-rose",
  "90037": "cdp-malbec",
  "90038": "cdp-pinot-noir",
  "90039": "cdp-rose",
  "90040": "cn-bianco",
  "90041": "cn-rosso",
  "90042": "corralejo-anejo",
  "90043": "corralejo-blanco",
  "90044": "corralejo-reposado",
  "90045": "dalmore-12",
  "90046": "dalmore-15",
  "90047": "dalmore-18",
  "90048": "dom-brut-nature",
  "90049": "dom-chardonnay",
  "90050": "dom-extra-brut",
  "90051": "dom-gran-blend",
  "90052": "dom-gran-cabernet",
  "90053": "dom-gran-malbec",
  "90054": "dom-malbec",
  "90055": "dom-malbec-cab-franc",
  "90056": "enc-brut-nature",
  "90057": "enc-cabernet",
  "90058": "enc-chardonnay",
  "90059": "enc-malbec",
  "90060": "fel-1997",
  "90061": "fel-1999",
  "90062": "fel-2009",
  "90063": "fel-2012",
  "90064": "fel-2013",
  "90065": "fel-2014",
  "90066": "fel-2015",
  "90067": "fel-2017",
  "90068": "giffard-maracuya",
  "90069": "giffard-menthe",
  "90070": "gm-12",
  "90071": "gm-chardonnay",
  "90072": "gvine-floraison",
  "90073": "gvine-nouaison",
  "90074": "june-peach",
  "90075": "jura-12",
  "90076": "jura-18",
  "90077": "jura-bourbon",
  "90078": "knuthansen",
  "90079": "lb-ds-cabernet-franc",
  "90080": "lb-ds-cabernet-sauvignon",
  "90081": "lb-ds-chardonnay",
  "90082": "lb-ds-corte",
  "90083": "lb-ds-malbec-altamira",
  "90084": "lb-ds-malbec-doc",
  "90085": "lb-ds-malbec-valle-uco",
  "90086": "lb-ds-white-blend",
  "90087": "lb-filos-chardonnay",
  "90088": "lb-leon-cabernet",
  "90089": "lb-los-nobles-malbec",
  "90090": "lb-paraiso",
  "90091": "louis-xiii",
  "90092": "lv-cabernet",
  "90093": "lv-chardonnay",
  "90094": "lv-le-dix",
  "90095": "lv-reserve-cabernet",
  "90096": "lv-reserve-carmenere",
  "90097": "lv-sauvignon-blanc",
  "90098": "mara-bonarda",
  "90099": "mara-cabernet-franc",
  "90100": "mara-malbec",
  "90101": "mara-merlot",
  "90102": "mara-petit-verdot",
  "90103": "mara-pinot-noir",
  "90104": "mara-semillon",
  "90105": "mermaid",
  "90106": "mermaid-pink",
  "90107": "mv-alteza",
  "90108": "mv-blanco",
  "90109": "mv-calcha",
  "90110": "mv-finca",
  "90111": "mv-imposible",
  "90112": "mv-mas-alla",
  "90113": "mv-pedregal",
  "90114": "mv-piedras-ladera",
  "90115": "mv-piedras-terrazas",
  "90116": "mv-tinto",
  "90117": "mv-vina-canota",
  "90118": "ojo-buen-cubero",
  "90119": "opihr",
  "90120": "otr-e80",
  "90121": "otr-merlot",
  "90122": "otr-pian-marroni",
  "90123": "otr-pinot-noir",
  "90124": "otr-sr69",
  "90125": "pc-10",
  "90126": "pc-18",
  "90127": "planteray-dark",
  "90128": "planteray-stiggins",
  "90129": "pravda-caramelo",
  "90130": "rdc-araucana-azul",
  "90131": "rdc-araucana-rdlc",
  "90132": "rdc-araucana-rose",
  "90133": "rdc-clasico-merlot",
  "90134": "rdc-especial-malbec",
  "90135": "rdc-patinas-blancas",
  "90136": "remy-vsop",
  "90137": "remy-xo",
  "90138": "ri-campo-del-cielo",
  "90139": "ri-cosmovision",
  "90140": "ri-simbiosis",
  "90141": "rut-encabezado-malbec",
  "90142": "rut-extra-brut",
  "90143": "rut-gewurztraminer",
  "90144": "rut-grapa",
  "90145": "rut-pinot-noir",
  "90146": "rut-riesling",
  "90147": "rut-rose-malbec",
  "90148": "rut-vin-doux",
  "90149": "santa-teresa-1796",
  "90150": "sc-amici-miei",
  "90151": "sc-barbera",
  "90152": "sc-cabernet-franc",
  "90153": "sc-malbec",
  "90154": "sc-omaggio-cab-franc",
  "90155": "sc-omaggio-viognier",
  "90156": "sc-petit-verdot",
  "90157": "siesta-adobe-magnum",
  "90158": "siesta-cab-franc",
  "90159": "siesta-cab-sauvignon",
  "90160": "siesta-doble-magnum",
  "90161": "siesta-estuche-x3",
  "90162": "siesta-lost",
  "90163": "siesta-malbec",
  "90164": "sj-el-burro",
  "90165": "sj-el-cabrito",
  "90166": "sj-el-zorrito",
  "90167": "sj-la-mantis",
  "90168": "sj-la-oveja",
  "90169": "sj-la-vaquita",
  "90170": "telmont",
  "90171": "vc-bramare-lujan-cs",
  "90172": "vc-bramare-lujan-mb",
  "90173": "vc-bramare-uco-chard",
  "90174": "vc-bramare-uco-mb",
  "90175": "vc-chanares-cab-franc",
  "90176": "vc-chanares-malbec",
  "90177": "vc-cobos-malbec",
  "90178": "vc-cocodrilo",
  "90179": "vc-felino-cabernet",
  "90180": "vc-felino-chardonnay",
  "90181": "vc-felino-malbec",
  "90182": "vc-hobbs-cabernet",
  "90183": "vc-hobbs-malbec",
  "90184": "vc-vinculum-chard",
  "90185": "vc-vinculum-malbec",
  "90186": "vc-volturno",
  "90187": "vc-zingaretti-chard",
  "90188": "vc-zingaretti-malbec",
  "90189": "vdl-condado-do-tea",
  "90190": "vdl-damaro-albarino",
  "90191": "vdl-iluminado-malbec",
  "90192": "vdl-iluminado-sangiovese",
  "90193": "vdl-iluminado-syrah",
  "90194": "vdl-iluminado-tempranillo",
  "90195": "vdl-rubios-albarino",
  "90196": "vdl-valcerracin-crianza",
  "90197": "vdl-valcerracin-rosado",
  "90198": "zuc-aluvional-gualtallary",
  "90199": "zuc-aluvional-los-chacayes",
  "90200": "zuc-aluvional-paraje-altamira",
  "90201": "zuc-aluvional-san-pablo",
  "90202": "zuc-botanico",
  "90203": "zuc-canal-uco",
  "90204": "zuc-concreto-malbec-2023",
  "90205": "zuc-concreto-malbec-2024",
  "90206": "zuc-emma-zuccardi-bonarda",
  "90207": "zuc-fosil",
  "90208": "zuc-gualtallary-cabernet-franc",
  "90209": "zuc-gualtallary-malbec",
  "90210": "zuc-jose-zuccardi-2016",
  "90211": "zuc-jose-zuccardi-2021",
  "90212": "zuc-las-cerrilladas",
  "90213": "zuc-las-cuchillas",
  "90214": "zuc-los-membrillos",
  "90215": "zuc-los-membrillos-semillon",
  "90216": "zuc-paraje-altamira-malbec-2019",
  "90217": "zuc-paraje-altamira-malbec-2023",
  "90218": "zuc-piedra-infinita",
  "90219": "zuc-piedra-infinita-gravascal-2020",
  "90220": "zuc-piedra-infinita-gravascal-2021",
  "90221": "zuc-piedra-infinita-supercal",
  "90222": "zuc-san-pablo-albarino",
  "90223": "zuc-san-pablo-cabernet-franc",
  "90224": "zuc-san-pablo-malbec",
  "90225": "zuc-san-pablo-riesling",
  "90226": "zuc-san-pablo-verdejo",
  "90227": "zuc-the-amphora-project-malbec",
  "90228": "zuc-tito-zuccardi",
  "90229": "zuc-tupungato-sauvignon-blanc",
  "90230": "zuc-tupungato-semillon",
  "90231": "zuc-vista-flores-chenin-blanc",
  "90232": "zuc-viticultor-valle-de-uco-crioll",
  "90233": "zuc-viticultor-valle-de-uco-tinto",

  "52554": "chivas-18",
  "52556": "chivas-ultis",
  "78": "royal-salute-21",
  "50689": "glenlivet-18",
  "14974": "longmorn-dc",
  "14975": "scapa-skiren",
  "14973": "aberlour-12",
  "54783": "aberlour-12",
  "52219": "scapa-glansa",
  "50246": "monkey47",
  "53208": "malfy-originale",
  "53210": "malfy-limone",
  "53209": "malfy-rosa",
  "11329": "havana-maestros",
  "12778": "absolut-elyx",
  "51818": "pj-grand-brut",
  "52143": "pj-blanc-blancs",
  "12765": "pj-belle-epoque",
  "51816": "mumm-cordon-rouge",
  "51517": "mumm-rose",
  "52142": "mumm-demi-sec",
  "4787": "dp-2017",
  "4633": "dp-vintage",
  "4438": "dp-2013",
  "4655": "dp-luminous",
  "4466": "dp-luminous",
  "4541": "dp-mag-2012",
  "4309": "dp-vintage",
  "4120": "dp-mag-2008",
  "4680": "dp-rose",
  "4308": "dp-rose-2008",
  "4194": "dp-rose-2006",
  "4467": "dp-p2-2004",
  "4623": "moet-nectar",
  "65": "moet-brut",
  "4121": "moet-golden",
  "4639": "moet-ice",
  "4749": "moet-gv",
  "3615": "moet-brut",
  "4637": "moet-rose",
  "2721": "moet-rose",
  "4470": "moet-gvr-2015",
  "4305": "moet-gvr-2013",
  "4285": "moet-rose",
  "4468": "moet-gv",
  "4304": "moet-gv-2013",
  "88": "hennessy-vs",
  "4414": "hennessy-vs-lum",
  "4396": "hennessy-vs",
  "91": "hennessy-vsop",
  "4643": "hennessy-xo",
  "3782": "hennessy-vs",
  "4380": "vc-yellow",
  "4642": "vc-yellow",
  "4499": "vc-rose",
  "4616": "vc-rich",
  "4538": "vc-gd",
  "4522": "vc-gd-rose",
  "4697": "vc-rich-rose",
  "4306": "vc-extra-old",
  "4021": "vc-vintage-rose",
  "4537": "vc-vintage-2015",
  "4751": "krug-gc",
  "4683": "cheval",
  "4684": "cheval",
  "4583": "cheval",
  "4475": "cheval",
  "4379": "cheval",
  "4242": "cheval",
  "4712": "terr-grand-malbec",
  "4713": "terr-grand-cab",
  "4711": "terr-grand-chard",
  "4368": "terr-grand-chard",
  "4648": "terr-petit-manseng",
  "4682": "terr-origen-chard",
  "4520": "terr-altamira",
  "4519": "terr-chacayes",
  "4518": "terr-compuertas",
  "4531": "terr-chacayes",
  "4485": "terr-grand-malbec",
  "4412": "terr-grand-malbec",
  "4484": "terr-grand-cab",
  "4413": "terr-grand-cab",
  "4483": "terr-grand-chard",
  "4488": "terr-petit-manseng",
  "4350": "terr-compuertas",
  "4393": "terr-chacayes",
  "4394": "terr-altamira",
  "51913": "arnaldo-b",
  "51914": "etchart",
};

function imageFor(sku: string) {
  const key = IMG_BY_SKU[sku];
  return key ? `/productos/${key}.jpg` : "/productos/dp-vintage.jpg";
}

// El filtro de la tienda las lista alfabéticamente desde la base, así que este
// orden no afecta cómo se ven. Brandy va aparte de Cognac a propósito: el
// Lepanto es brandy de Jerez y cognac es denominación de origen francesa.
const categories = [
  { name: "Whisky",    slug: "whisky" },
  { name: "Champagne", slug: "champagne" },
  { name: "Cognac",    slug: "cognac" },
  { name: "Brandy",    slug: "brandy" },
  { name: "Gin",       slug: "gin" },
  { name: "Vodka",     slug: "vodka" },
  { name: "Ron",       slug: "ron" },
  { name: "Tequila",   slug: "tequila" },
  { name: "Pisco",     slug: "pisco" },
  { name: "Licores",   slug: "licores" },
  { name: "Vinos",     slug: "vinos" },
  { name: "Espumantes", slug: "espumantes" },
  { name: "Vermouth",  slug: "vermouth" },
  { name: "Estuches y regalos", slug: "estuches" },
];

type ProductInput = {
  name: string;
  sku: string;
  brand: string;
  origin: string;
  categorySlug: string;
  checkoutMode: "WEB" | "CONSULTAR";
  featured?: boolean;
  isExclusive?: boolean;
};

// slug seguro desde nombre + SKU
function toSlug(name: string, sku: string) {
  return name
    .toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") + "-" + sku;
}

const products: ProductInput[] = [
  // ─── WHISKY ────────────────────────────────────────────────────────────────
  { name: "Chivas Regal 18 YO", sku: "52554", brand: "Chivas Regal", origin: "Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Chivas Regal Ultis", sku: "52556", brand: "Chivas Regal", origin: "Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Royal Salute 21 YO", sku: "78", brand: "Royal Salute", origin: "Escocia", categorySlug: "whisky", checkoutMode: "WEB", featured: true },
  { name: "The Glenlivet 18 YO", sku: "50689", brand: "The Glenlivet", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Longmorn Distiller's Choice", sku: "14974", brand: "Longmorn", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Scapa Skiren", sku: "14975", brand: "Scapa", origin: "Orkney, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Aberlour 12 YO (caja 3)", sku: "14973", brand: "Aberlour", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Aberlour 12 YO", sku: "54783", brand: "Aberlour", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Scapa Glansa", sku: "52219", brand: "Scapa", origin: "Orkney, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },

  // ─── GIN ───────────────────────────────────────────────────────────────────
  { name: "Monkey 47 Dry Gin", sku: "50246", brand: "Monkey 47", origin: "Selva Negra, Alemania", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Gin Malfy Original", sku: "53208", brand: "Malfy", origin: "Torino, Italia", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Gin Malfy Limone", sku: "53210", brand: "Malfy", origin: "Torino, Italia", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Gin Malfy Pink", sku: "53209", brand: "Malfy", origin: "Torino, Italia", categorySlug: "gin", checkoutMode: "WEB" },

  // ─── RON ───────────────────────────────────────────────────────────────────
  { name: "Havana Club Selección de Maestros", sku: "11329", brand: "Havana Club", origin: "Cuba", categorySlug: "ron", checkoutMode: "WEB" },

  // ─── VODKA ─────────────────────────────────────────────────────────────────
  { name: "Absolut Elyx", sku: "12778", brand: "Absolut", origin: "Åhus, Suecia", categorySlug: "vodka", checkoutMode: "WEB" },

  // ─── CHAMPAGNE — Perrier-Jouët & GH Mumm ──────────────────────────────────
  { name: "Perrier-Jouët Grand Brut", sku: "51818", brand: "Perrier-Jouët", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Perrier-Jouët Blanc de Blancs", sku: "52143", brand: "Perrier-Jouët", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Perrier-Jouët Belle Époque", sku: "12765", brand: "Perrier-Jouët", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB", isExclusive: true },
  { name: "GH Mumm Cordon Rouge", sku: "51816", brand: "GH Mumm", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "GH Mumm Grand Cordon Rosé", sku: "51517", brand: "GH Mumm", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "GH Mumm Olympe Demi Sec", sku: "52142", brand: "GH Mumm", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },

  // ─── CHAMPAGNE — Dom Pérignon ──────────────────────────────────────────────
  { name: "Dom Pérignon Blanc Vintage 2017", sku: "4787", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB", featured: true },
  { name: "Dom Pérignon Blanc Vintage 2015", sku: "4633", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Dom Pérignon Blanc Vintage 2013", sku: "4438", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Dom Pérignon Luminous Label 2015", sku: "4655", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  // CONSULTAR
  { name: "Dom Pérignon Luminous Label 2013", sku: "4466", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Blanc Vintage 2012 Magnum", sku: "4541", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Blanc Vintage 2010 Magnum", sku: "4309", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Blanc Vintage 2008 Magnum", sku: "4120", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Rosé Vintage 2009", sku: "4680", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Rosé Vintage 2008", sku: "4308", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon Rosé Vintage 2006", sku: "4194", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Dom Pérignon P2 Vintage 2004", sku: "4467", brand: "Dom Pérignon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },

  // ─── CHAMPAGNE — Moët & Chandon ────────────────────────────────────────────
  { name: "Moët & Chandon Nectar Impérial", sku: "4623", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Brut Impérial", sku: "65", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Brut Imperial Golden", sku: "4121", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Ice Impérial", sku: "4639", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Grand Vintage Brut 2016", sku: "4749", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon MCIII", sku: "3615", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB", isExclusive: true },
  { name: "Moët & Chandon Brut Rosé", sku: "4637", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Rosé Impérial", sku: "2721", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Grand Vintage Rosé 2015", sku: "4470", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Grand Vintage Rosé 2013", sku: "4305", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Moët & Chandon Rosé Imperial EOY21", sku: "4285", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  // CONSULTAR
  { name: "Moët & Chandon Grand Vintage Brut 2015", sku: "4468", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Moët & Chandon Grand Vintage Brut 2013", sku: "4304", brand: "Moët & Chandon", origin: "Épernay, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },

  // ─── COGNAC — Hennessy ─────────────────────────────────────────────────────
  { name: "Hennessy V.S.", sku: "88", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB" },
  { name: "Hennessy V.S. Luminous 2022", sku: "4414", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB" },
  { name: "Hennessy V.S. Magnum", sku: "4396", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB" },
  { name: "Hennessy V.S.O.P.", sku: "91", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB" },
  { name: "Hennessy X.O.", sku: "4643", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB", isExclusive: true, featured: true },
  // CONSULTAR
  { name: "Hennessy V.S. 20cl", sku: "3782", brand: "Hennessy", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "CONSULTAR" },

  // ─── CHAMPAGNE — Veuve Clicquot ────────────────────────────────────────────
  { name: "Veuve Clicquot Yellow Label Brut", sku: "4380", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Veuve Clicquot Yellow Label Brut Magnum", sku: "4642", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Veuve Clicquot Brut Rosé", sku: "4499", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Veuve Clicquot Rich On Ice", sku: "4616", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Veuve Clicquot La Grande Dame Brut", sku: "4538", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB", isExclusive: true, featured: true },
  { name: "Veuve Clicquot La Grande Dame Rosé", sku: "4522", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB", isExclusive: true },
  { name: "Veuve Clicquot Rich Rosé On Ice", sku: "4697", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  // CONSULTAR
  { name: "Veuve Clicquot Extra Brut Extra Old", sku: "4306", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Veuve Clicquot Vintage 2012 Rosé", sku: "4021", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Veuve Clicquot Vintage Reserve 2015", sku: "4537", brand: "Veuve Clicquot", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true },

  // ─── CHAMPAGNE — Krug ──────────────────────────────────────────────────────
  { name: "Krug Grande Cuvée 173ème Édition", sku: "4751", brand: "Krug", origin: "Reims, Francia", categorySlug: "champagne", checkoutMode: "CONSULTAR", isExclusive: true, featured: true },

  // ─── VINOS — Cheval des Andes ──────────────────────────────────────────────
  { name: "Cheval des Andes 2022", sku: "4683", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB", featured: true },
  { name: "Cheval des Andes 2022 Magnum", sku: "4684", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cheval des Andes 2021", sku: "4583", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  // CONSULTAR
  { name: "Cheval des Andes 2020", sku: "4475", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Cheval des Andes 2019", sku: "4379", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Cheval des Andes 2018", sku: "4242", brand: "Cheval des Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },

  // ─── VINOS — Terrazas de los Andes ─────────────────────────────────────────
  { name: "Terrazas Grand Malbec 2022", sku: "4712", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Grand Cabernet Sauvignon 2022", sku: "4713", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Grand Chardonnay 2023", sku: "4711", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Grand Chardonnay 2021", sku: "4368", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Petit Manseng 2021", sku: "4648", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Origen Chardonnay 2025", sku: "4682", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Origen Altamira MB/CS 2022", sku: "4520", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Origen Los Chacayes MB 2022", sku: "4519", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Origen Las Compuertas MB 2022", sku: "4518", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Terrazas Origen Caja Combinada", sku: "4531", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  // CONSULTAR
  { name: "Terrazas Grand Malbec 2021", sku: "4485", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Grand Malbec 2020", sku: "4412", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Grand Cabernet Sauvignon 2021", sku: "4484", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Grand Cabernet Sauvignon 2020", sku: "4413", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Grand Chardonnay 2022", sku: "4483", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Petit Manseng 2020", sku: "4488", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Origen Las Compuertas MB 2021", sku: "4350", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Origen Los Chacayes MB 2021", sku: "4393", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },
  { name: "Terrazas Origen Paraje Altamira MB/CS 2021", sku: "4394", brand: "Terrazas de los Andes", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR", isExclusive: true },

  // ─── VINOS — Cosechas Históricas ───────────────────────────────────────────
  { name: "Arnaldo B 3 Litros", sku: "51913", brand: "Arnaldo B", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB", isExclusive: true },
  { name: "Etchart Cosecha 92", sku: "51914", brand: "Etchart", origin: "Salta, Argentina", categorySlug: "vinos", checkoutMode: "WEB", isExclusive: true },

  // ─── INCORPORACIONES DE AGOSTO DE 2026 ─────────────────────────────────────
  // Zuccardi, Viña Cobos, Luigi Bosca, Matervini, Alma Mater, AlmaNegra, Mara
  // de Uco, Siesta, On The Road, Stella Crinita, Cuchillo de Palo, Ribera del
  // Cuarzo, Los Vascos, CARO, Cantieri Navali, Rutini, Vinos de la Luz, Santa
  // Julia, Barsol y las piezas de whisky, cognac, gin y ron conseguidas de
  // tiendas. El SKU es interno y correlativo: Souverain todavía no pasó el suyo
  // para estas listas.
  { name: "Alma Mater Brut Nature Blanco", sku: "90001", brand: "Alma Mater", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Alma Mater Brut Nature Rosado", sku: "90002", brand: "Alma Mater", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Alma Mater Cabernet Franc · Cabernet Sauvignon", sku: "90003", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Alma Mater Chardonnay", sku: "90004", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Alma Mater GSM", sku: "90005", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Alma Mater Malbec", sku: "90006", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Alma Mater Pinot Noir", sku: "90007", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Alma Mater Semillón", sku: "90008", brand: "Alma Mater", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "AlmaNegra Blanc de Blancs Magnum 1,5 L", sku: "90009", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "CONSULTAR" },
  { name: "AlmaNegra Blanc de Blancs", sku: "90010", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "AlmaNegra Blanco", sku: "90011", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "AlmaNegra Brut Nature Rosé", sku: "90012", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Gran AlmaNegra Magnum 1,5 L", sku: "90013", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "estuches", checkoutMode: "CONSULTAR" },
  { name: "Gran AlmaNegra Magnum Espumante 1,5 L", sku: "90014", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "estuches", checkoutMode: "CONSULTAR" },
  { name: "AlmaNegra Orange", sku: "90015", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "AlmaNegra Tinto", sku: "90016", brand: "AlmaNegra", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Pisco Acholado Barsol", sku: "90017", brand: "Barsol", origin: "Ica, Perú", categorySlug: "pisco", checkoutMode: "WEB" },
  { name: "Pisco Italia Barsol", sku: "90018", brand: "Barsol", origin: "Ica, Perú", categorySlug: "pisco", checkoutMode: "WEB" },
  { name: "Pisco Moscatel Barsol", sku: "90019", brand: "Barsol", origin: "Ica, Perú", categorySlug: "pisco", checkoutMode: "WEB" },
  { name: "Pisco Quebranta Barsol", sku: "90020", brand: "Barsol", origin: "Ica, Perú", categorySlug: "pisco", checkoutMode: "WEB" },
  { name: "Pisco Torontel Barsol", sku: "90021", brand: "Barsol", origin: "Ica, Perú", categorySlug: "pisco", checkoutMode: "WEB" },
  { name: "Bruichladdich 18 Años", sku: "90022", brand: "Bruichladdich", origin: "Islay, Escocia", categorySlug: "whisky", checkoutMode: "CONSULTAR" },
  { name: "Bruichladdich 30 Años", sku: "90023", brand: "Bruichladdich", origin: "Islay, Escocia", categorySlug: "whisky", checkoutMode: "CONSULTAR" },
  { name: "Aruma Malbec", sku: "90024", brand: "Bodegas CARO", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "CARO", sku: "90025", brand: "Bodegas CARO", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Petit CARO", sku: "90026", brand: "Bodegas CARO", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Petit CARO 5 L", sku: "90027", brand: "Bodegas CARO", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Casa de Herrero Cabernet Franc", sku: "90028", brand: "Casa de Herrero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Casa de Herrero Corte de Blancas", sku: "90029", brand: "Casa de Herrero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Casa de Herrero Malbec", sku: "90030", brand: "Casa de Herrero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Casa de Herrero Pinot Noir", sku: "90031", brand: "Casa de Herrero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Casa de Herrero Rosé de Pinot Noir", sku: "90032", brand: "Casa de Herrero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Cabernet Franc", sku: "90033", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Corte de Blancas", sku: "90034", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Extra Brut Blanco", sku: "90035", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Extra Brut Rosado", sku: "90036", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Malbec", sku: "90037", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Pinot Noir", sku: "90038", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cuchillo de Palo Rosé de Pinot Noir", sku: "90039", brand: "Cuchillo de Palo", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cantieri Navali Bianco", sku: "90040", brand: "Cantieri Navali", origin: "Mendoza, Argentina", categorySlug: "vermouth", checkoutMode: "WEB" },
  { name: "Cantieri Navali Rosso", sku: "90041", brand: "Cantieri Navali", origin: "Mendoza, Argentina", categorySlug: "vermouth", checkoutMode: "WEB" },
  { name: "Corralejo Añejo", sku: "90042", brand: "Corralejo", origin: "Guanajuato, México", categorySlug: "tequila", checkoutMode: "WEB" },
  { name: "Corralejo Blanco", sku: "90043", brand: "Corralejo", origin: "Guanajuato, México", categorySlug: "tequila", checkoutMode: "WEB" },
  { name: "Corralejo Reposado", sku: "90044", brand: "Corralejo", origin: "Guanajuato, México", categorySlug: "tequila", checkoutMode: "WEB" },
  { name: "The Dalmore 12 Años", sku: "90045", brand: "The Dalmore", origin: "Highlands, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "The Dalmore 15 Años", sku: "90046", brand: "The Dalmore", origin: "Highlands, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "The Dalmore 18 Años", sku: "90047", brand: "The Dalmore", origin: "Highlands, Escocia", categorySlug: "whisky", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Espumoso Brut Nature", sku: "90048", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Chardonnay", sku: "90049", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Espumoso Extra Brut", sku: "90050", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Gran Blend", sku: "90051", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Gran Cabernet Sauvignon", sku: "90052", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Gran Malbec", sku: "90053", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Malbec", sku: "90054", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Dominio Rutini Malbec · Cabernet Franc", sku: "90055", brand: "Dominio Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Encuentro Espumoso Pinot Noir Brut Nature", sku: "90056", brand: "Encuentro", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "CONSULTAR" },
  { name: "Encuentro Cabernet Sauvignon", sku: "90057", brand: "Encuentro", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Encuentro Chardonnay", sku: "90058", brand: "Encuentro", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Encuentro Malbec", sku: "90059", brand: "Encuentro", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 1997", sku: "90060", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 1999", sku: "90061", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2009", sku: "90062", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2012", sku: "90063", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2013", sku: "90064", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2014", sku: "90065", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2015", sku: "90066", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Felipe Rutini 2017", sku: "90067", brand: "Felipe Rutini", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Giffard Licor de Maracuyá", sku: "90068", brand: "Giffard", origin: "Angers, Francia", categorySlug: "licores", checkoutMode: "WEB" },
  { name: "Giffard Menthe Pastille", sku: "90069", brand: "Giffard", origin: "Angers, Francia", categorySlug: "licores", checkoutMode: "WEB" },
  { name: "Glen Moray Heritage 12 Años", sku: "90070", brand: "Glen Moray", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Glen Moray Classic Chardonnay Cask", sku: "90071", brand: "Glen Moray", origin: "Speyside, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "G'Vine Floraison", sku: "90072", brand: "G'Vine", origin: "Cognac, Francia", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Nouaison by G'Vine", sku: "90073", brand: "G'Vine", origin: "Cognac, Francia", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "June by G'Vine Peach", sku: "90074", brand: "G'Vine", origin: "Cognac, Francia", categorySlug: "licores", checkoutMode: "WEB" },
  { name: "Jura 12 Años", sku: "90075", brand: "Jura", origin: "Isle of Jura, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Jura 18 Años", sku: "90076", brand: "Jura", origin: "Isle of Jura, Escocia", categorySlug: "whisky", checkoutMode: "CONSULTAR" },
  { name: "Jura Bourbon Cask", sku: "90077", brand: "Jura", origin: "Isle of Jura, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Knut Hansen Dry Gin 500 ml", sku: "90078", brand: "Knut Hansen", origin: "Hamburgo, Alemania", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "De Sangre Cabernet Franc", sku: "90079", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Cabernet Sauvignon", sku: "90080", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Chardonnay", sku: "90081", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Corte", sku: "90082", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Malbec Altamira", sku: "90083", brand: "Luigi Bosca", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Malbec D.O.C", sku: "90084", brand: "Luigi Bosca", origin: "Luján de Cuyo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre Malbec Valle de Uco", sku: "90085", brand: "Luigi Bosca", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "De Sangre White Blend", sku: "90086", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Filos Chardonnay", sku: "90087", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "León Cabernet Sauvignon", sku: "90088", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Los Nobles Malbec D.O.C", sku: "90089", brand: "Luigi Bosca", origin: "Vistalba, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Luigi Bosca Paraíso", sku: "90090", brand: "Luigi Bosca", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Louis XIII by Rémy Martin", sku: "90091", brand: "Rémy Martin", origin: "Grande Champagne, Francia", categorySlug: "cognac", checkoutMode: "CONSULTAR" },
  { name: "Las Huertas Cabernet Sauvignon", sku: "90092", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Las Huertas Chardonnay", sku: "90093", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Le Dix de Los Vascos", sku: "90094", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Las Huertas Estate Reserve Cabernet Sauvignon", sku: "90095", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Las Huertas Estate Reserve Carmenère", sku: "90096", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Las Huertas Sauvignon Blanc", sku: "90097", brand: "Los Vascos", origin: "Valle de Colchagua, Chile", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Bonarda", sku: "90098", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Cabernet Franc", sku: "90099", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Malbec", sku: "90100", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Merlot", sku: "90101", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Petit Verdot", sku: "90102", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Pinot Noir", sku: "90103", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mara Semillón", sku: "90104", brand: "Mara de Uco", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Mermaid Gin", sku: "90105", brand: "Isle of Wight Distillery", origin: "Isle of Wight, Inglaterra", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Mermaid Pink Gin", sku: "90106", brand: "Isle of Wight Distillery", origin: "Isle of Wight, Inglaterra", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "Alteza", sku: "90107", brand: "Matervini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Matervini Blanco", sku: "90108", brand: "Matervini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Calcha", sku: "90109", brand: "Matervini", origin: "Valles Calchaquíes, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Matervini Finca", sku: "90110", brand: "Matervini", origin: "Perdriel, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Imposible", sku: "90111", brand: "Matervini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Más Allá", sku: "90112", brand: "Matervini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Pedregal", sku: "90113", brand: "Matervini", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Piedras Viejas Laderas", sku: "90114", brand: "Matervini", origin: "El Challao, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Piedras Viejas Terrazas", sku: "90115", brand: "Matervini", origin: "El Challao, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Matervini Tinto", sku: "90116", brand: "Matervini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Viña Canota", sku: "90117", brand: "Matervini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Ojo de Buen Cubero Malbec", sku: "90118", brand: "Ojo de Buen Cubero", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Opihr Oriental Spiced Gin", sku: "90119", brand: "Opihr", origin: "Inglaterra", categorySlug: "gin", checkoutMode: "WEB" },
  { name: "On The Road E80", sku: "90120", brand: "On The Road", origin: "Toscana, Italia", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "On The Road Merlot", sku: "90121", brand: "On The Road", origin: "Patagonia, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Pian del Marroni", sku: "90122", brand: "On The Road", origin: "Toscana, Italia", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "On The Road Pinot Noir", sku: "90123", brand: "On The Road", origin: "Patagonia, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "On The Road SR69", sku: "90124", brand: "On The Road", origin: "Toscana, Italia", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Port Charlotte 10 Años", sku: "90125", brand: "Port Charlotte", origin: "Islay, Escocia", categorySlug: "whisky", checkoutMode: "WEB" },
  { name: "Port Charlotte 18 Años", sku: "90126", brand: "Port Charlotte", origin: "Islay, Escocia", categorySlug: "whisky", checkoutMode: "CONSULTAR" },
  { name: "Planteray Original Dark", sku: "90127", brand: "Planteray", origin: "Francia", categorySlug: "ron", checkoutMode: "WEB" },
  { name: "Planteray Stiggins' Fancy Pineapple", sku: "90128", brand: "Planteray", origin: "Francia", categorySlug: "ron", checkoutMode: "WEB" },
  { name: "Vodka Pravda Caramelo", sku: "90129", brand: "Pravda", origin: "Polonia", categorySlug: "vodka", checkoutMode: "WEB" },
  { name: "Araucana Azul", sku: "90130", brand: "Ribera del Cuarzo", origin: "Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Araucana Río de los Ciervos", sku: "90131", brand: "Ribera del Cuarzo", origin: "Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Araucana Río de los Ciervos Malbec Rosé", sku: "90132", brand: "Ribera del Cuarzo", origin: "Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Ribera del Cuarzo Clásico Merlot", sku: "90133", brand: "Ribera del Cuarzo", origin: "Valle Azul, Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Ribera del Cuarzo Especial Malbec", sku: "90134", brand: "Ribera del Cuarzo", origin: "Valle Azul, Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Ribera del Cuarzo Clásico Pátinas Blancas", sku: "90135", brand: "Ribera del Cuarzo", origin: "Valle Azul, Río Negro, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Rémy Martin V.S.O.P", sku: "90136", brand: "Rémy Martin", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "WEB" },
  { name: "Rémy Martin X.O.", sku: "90137", brand: "Rémy Martin", origin: "Cognac, Francia", categorySlug: "cognac", checkoutMode: "CONSULTAR" },
  { name: "Campo del Cielo Blanco Macerado", sku: "90138", brand: "Radical Imagination", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Cosmovisión Naranjo", sku: "90139", brand: "Radical Imagination", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Simbiosis Pet Nat Rosé", sku: "90140", brand: "Radical Imagination", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Rutini Encabezado de Malbec 500 ml", sku: "90141", brand: "Rutini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Rutini Espumoso Extra Brut", sku: "90142", brand: "Rutini", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "CONSULTAR" },
  { name: "Rutini Gewürztraminer", sku: "90143", brand: "Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Rutini Grapa · Destilado de Orujo de Malbec 500 ml", sku: "90144", brand: "Rutini", origin: "Mendoza, Argentina", categorySlug: "licores", checkoutMode: "CONSULTAR" },
  { name: "Rutini Pinot Noir", sku: "90145", brand: "Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Rutini Riesling", sku: "90146", brand: "Rutini", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Rutini Rosé de Malbec", sku: "90147", brand: "Rutini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Rutini Vin Doux Naturel 500 ml", sku: "90148", brand: "Rutini", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Santa Teresa 1796", sku: "90149", brand: "Santa Teresa", origin: "Aragua, Venezuela", categorySlug: "ron", checkoutMode: "WEB" },
  { name: "Stella Crinita Amici Miei", sku: "90150", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Stella Crinita Barbera", sku: "90151", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Stella Crinita Cabernet Franc", sku: "90152", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Stella Crinita Malbec", sku: "90153", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Omaggio Cabernet Franc Pet Nat", sku: "90154", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Omaggio Viognier Pet Nat", sku: "90155", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Stella Crinita Petit Verdot", sku: "90156", brand: "Stella Crinita", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Adobe Magnum Gran Siesta 1,5 L", sku: "90157", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Siesta Cabernet Franc Single Vineyard", sku: "90158", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Siesta Cabernet Sauvignon Single Vineyard", sku: "90159", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Doble Magnum Gran Siesta 3 L", sku: "90160", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Estuche de Madera Siesta Malbec x3", sku: "90161", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "estuches", checkoutMode: "CONSULTAR" },
  { name: "Lost by Siesta Malbec del Laberinto", sku: "90162", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Siesta Malbec Single Vineyard", sku: "90163", brand: "Siesta en el Tahuán", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Santa Julia El Burro Malbec Natural", sku: "90164", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Santa Julia El Cabrito Cabernet Sauvignon Natural", sku: "90165", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Santa Julia El Zorrito Naranjo", sku: "90166", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Santa Julia La Mantis Pet Nat", sku: "90167", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "espumantes", checkoutMode: "WEB" },
  { name: "Santa Julia La Oveja Blanco Natural", sku: "90168", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Santa Julia La Vaquita Clarete de Malbec", sku: "90169", brand: "Santa Julia", origin: "Maipú, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Champagne Telmont Réserve Brut", sku: "90170", brand: "Telmont", origin: "Damery, Francia", categorySlug: "champagne", checkoutMode: "WEB" },
  { name: "Bramare Luján de Cuyo Cabernet Sauvignon", sku: "90171", brand: "Viña Cobos", origin: "Luján de Cuyo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Bramare Luján de Cuyo Malbec", sku: "90172", brand: "Viña Cobos", origin: "Luján de Cuyo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Bramare Valle de Uco Chardonnay", sku: "90173", brand: "Viña Cobos", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Bramare Valle de Uco Malbec", sku: "90174", brand: "Viña Cobos", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Chañares Estate Cabernet Franc", sku: "90175", brand: "Viña Cobos", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Chañares Estate Malbec", sku: "90176", brand: "Viña Cobos", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Cobos Malbec", sku: "90177", brand: "Viña Cobos", origin: "Perdriel, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Cocodrilo Corte", sku: "90178", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Felino Cabernet Sauvignon", sku: "90179", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Felino Chardonnay", sku: "90180", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Felino Malbec", sku: "90181", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Hobbs Estate Cabernet Sauvignon", sku: "90182", brand: "Viña Cobos", origin: "Perdriel, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Hobbs Estate Malbec", sku: "90183", brand: "Viña Cobos", origin: "Perdriel, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Vinculum Chardonnay", sku: "90184", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Vinculum Malbec", sku: "90185", brand: "Viña Cobos", origin: "Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Volturno Cabernet Sauvignon", sku: "90186", brand: "Viña Cobos", origin: "Perdriel, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Zingaretti Estate Chardonnay", sku: "90187", brand: "Viña Cobos", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Zingaretti Estate Malbec", sku: "90188", brand: "Viña Cobos", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Señorío de Rubiós Condado do Tea Gran Coupage", sku: "90189", brand: "Señorío de Rubiós", origin: "Rías Baixas, España", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Manuel D'Amaro Albariño", sku: "90190", brand: "Manuel D'Amaro", origin: "Rías Baixas, España", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Iluminado Argentina Malbec", sku: "90191", brand: "Vinos de la Luz", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Iluminado Italia Sangiovese", sku: "90192", brand: "Vinos de la Luz", origin: "Montalcino, Toscana, Italia", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Iluminado EEUU Syrah", sku: "90193", brand: "Vinos de la Luz", origin: "Santa María Valley, California", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Iluminado España Tempranillo", sku: "90194", brand: "Vinos de la Luz", origin: "Peñafiel, Ribera del Duero, España", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Señorío de Rubiós Albariño", sku: "90195", brand: "Señorío de Rubiós", origin: "Rías Baixas, España", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Pagos de Valcerracín Tempranillo Crianza", sku: "90196", brand: "Pagos de Valcerracín", origin: "Ribera del Duero, España", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Valcerracín Rosado", sku: "90197", brand: "Pagos de Valcerracín", origin: "Cigales, España", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Aluvional Gualtallary", sku: "90198", brand: "Zuccardi", origin: "Gualtallary, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Aluvional Los Chacayes", sku: "90199", brand: "Zuccardi", origin: "Los Chacayes, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Aluvional Paraje Altamira", sku: "90200", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Aluvional San Pablo", sku: "90201", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Botánico", sku: "90202", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Canal Uco", sku: "90203", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Zuccardi Concreto Malbec 2023", sku: "90204", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Zuccardi Concreto Malbec 2024", sku: "90205", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Emma Zuccardi Bonarda", sku: "90206", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Fósil", sku: "90207", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Polígonos Gualtallary Cabernet Franc", sku: "90208", brand: "Zuccardi", origin: "Gualtallary, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos Gualtallary Malbec", sku: "90209", brand: "Zuccardi", origin: "Gualtallary, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "José Zuccardi 2016 Magnum 1,5 L", sku: "90210", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "José Zuccardi 2021", sku: "90211", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Las Cerrilladas", sku: "90212", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Las Cuchillas", sku: "90213", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Los Membrillos", sku: "90214", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Finca Los Membrillos Semillón", sku: "90215", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Polígonos Paraje Altamira Malbec 2019 Magnum 1,5 L", sku: "90216", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Polígonos Paraje Altamira Malbec 2023", sku: "90217", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Finca Piedra Infinita", sku: "90218", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Piedra Infinita Gravascal 2020", sku: "90219", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Piedra Infinita Gravascal 2021", sku: "90220", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Piedra Infinita Supercal", sku: "90221", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Polígonos San Pablo Albariño", sku: "90222", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos San Pablo Cabernet Franc", sku: "90223", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos San Pablo Malbec", sku: "90224", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos San Pablo Riesling", sku: "90225", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos San Pablo Verdejo", sku: "90226", brand: "Zuccardi", origin: "San Pablo, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "The Amphora Project Malbec", sku: "90227", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Tito Zuccardi", sku: "90228", brand: "Zuccardi", origin: "Paraje Altamira, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "CONSULTAR" },
  { name: "Polígonos Tupungato Sauvignon Blanc", sku: "90229", brand: "Zuccardi", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos Tupungato Semillón", sku: "90230", brand: "Zuccardi", origin: "Tupungato, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Polígonos Vista Flores Chenin Blanc", sku: "90231", brand: "Zuccardi", origin: "Vista Flores, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Viticultor Valle de Uco Criolla Chica", sku: "90232", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
  { name: "Viticultor Valle de Uco Tinto", sku: "90233", brand: "Zuccardi", origin: "Valle de Uco, Mendoza, Argentina", categorySlug: "vinos", checkoutMode: "WEB" },
];

async function main() {
  // Los pedidos NO se borran. La versión anterior arrancaba con
  // orderItem.deleteMany() y order.deleteMany(), así que recargar el catálogo
  // se llevaba puesto el historial de ventas. Mientras no haya pedidos da lo
  // mismo, pero en cuanto empiecen a vender sería una pérdida irreversible.
  const pedidos = await prisma.order.count();
  if (pedidos > 0) {
    console.log(`Hay ${pedidos} pedidos registrados: se conservan.`);
  }

  console.log("Limpiando el catálogo anterior...");
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  // Sólo se crean las categorías que tienen piezas: una vacía aparece igual en
  // el filtro de la tienda y lleva a un listado sin resultados.
  const conPiezas = new Set(products.map((p) => p.categorySlug));
  const usadas = categories.filter((c) => conPiezas.has(c.slug));
  console.log(`Creando ${usadas.length} categorías de ${categories.length}...`);
  const catMap: Record<string, string> = {};
  for (const cat of usadas) {
    const c = await prisma.category.create({ data: cat });
    catMap[cat.slug] = c.id;
  }

  console.log(`Creando ${products.length} productos...`);
  for (const p of products) {
    const imageUrl = imageFor(p.sku);
    await prisma.product.create({
      data: {
        name: p.name,
        slug: toSlug(p.name, p.sku),
        sku: p.sku,
        description: `${p.brand} — ${p.name}. Disponible para distribución exclusiva.`,
        tastingNotes: "Consultar con nuestro equipo para notas de cata detalladas.",
        origin: p.origin,
        brand: p.brand,
        categoryId: catMap[p.categorySlug],
        price: 0,
        stock: p.checkoutMode === "CONSULTAR" ? 1 : 6,
        imageUrl,
        checkoutMode: p.checkoutMode,
        featured: p.featured ?? false,
        isExclusive: p.isExclusive ?? false,
      },
    });
  }

  console.log(`✓ ${products.length} productos creados.`);
  console.log(`  WEB: ${products.filter(p => p.checkoutMode === "WEB").length}`);
  console.log(`  CONSULTAR: ${products.filter(p => p.checkoutMode === "CONSULTAR").length}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
